apiVersion: operator.projectsesame.io/v1alpha1
kind: Sesame
metadata:
  name: sesame-sample
  namespace: sesame-operator
spec:
  networkPublishing:
    envoy:
      type: NodePortService
      # nodePorts are auto-assigned by k8s if unspecified.
      nodePorts:
        - name: http
          portNumber: 30080
        - name: https
          portNumber: 30443
